# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: save_data.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "treatment.ParamsSave" do
    optional :data, :int32, 1
  end
  add_message "treatment.ResultSave" do
    optional :saved, :bool, 1
    optional :result, :int32, 2
  end
end

module Treatment
  ParamsSave = Google::Protobuf::DescriptorPool.generated_pool.lookup("treatment.ParamsSave").msgclass
  ResultSave = Google::Protobuf::DescriptorPool.generated_pool.lookup("treatment.ResultSave").msgclass
end
