# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: calculator.proto for package 'calculator'

require 'grpc'
require 'calculator_pb'

module Calculator
  module Transaction
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'calculator.Transaction'

      rpc :Multi, stream(Params), Result
      rpc :OneByOne, stream(Params), stream(Result)
      rpc :One, Params, Result
    end

    Stub = Service.rpc_stub_class
  end
end
